### ISSUE TITLE
Missing event types

### ISSUE THREAD

**Issue by neilstevenson** [tolitius/chazel#5]
Hazelcast 3.11 introduced a new event type, "LOADED"

See https://docs.hazelcast.org/docs/3.12.1/javadoc/com/hazelcast/core/EntryEventType.html#LOADED

This is missing from https://github.com/tolitius/chazel/blob/master/src/chazel/core.clj#L18
but the list isn't complete anyway as there are EXPIRED and REMOVED events that don't seem to be covered

**Comment by tolitius** [comment]
`[chazel "0.1.18"]` is updated to the latest Hazelcast (`3.12.1`) and has all the listeners.

let me know whether it works for you.

**Comment by neilstevenson** [comment]
I don't have the Clojure knowledge to test this. If tests pass I'm happy
